version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORT=${PORT}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - PHX_HOST=${PHX_HOST}
    ports:
      - 4001:4001
