version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORT=${PORT}
    ports:
      - 4001:4001
