version: '3.8'
services:
  web:
    # Overrides default command so the development container keeps running until the user disconnects
    command: /bin/bash -c "while sleep 1000; do :; done"
    volumes:
      - .:/usr/src/web
      - ../.git/:/usr/src/.git/ # Ensure git works in the devcontainer since this is a submodule
      - /web/_build
      - /web/deps
